"use client"
import { DataTable } from "./data-table";
import { columns } from "./columns";
import { useEffect, useState } from "react";

export default function page() {
  const [projects, setProjects] = useState([]);

  const fetchProjects = async () => {
    try {
      const res = await fetch("http://127.0.0.1:8001/api/admin/projects", {
        headers: {
          Authorization: `Token ${localStorage.getItem("token")}`,
        },
      });
      const data = await res.json();
      setProjects(data);
    } catch {
      setProjects([
        {
          id: 1,
          project_name: "Mobile App Development",
          status: "in_progress",
          created_date: "2024-01-06",
          due_date: "2024-04-05",
          created_by: "Sarah Smith",
        },
        {
          id: 2,
          project_name: "Cloud Migration",
          status: "completed",
          created_date: "2024-01-11",
          due_date: "2024-04-10",
          created_by: "John Doe",
        },
        {
          id: 3,
          project_name: "E-commerce Platform",
          status: "pending",
          created_date: "2024-01-16",
          due_date: "2024-04-15",
          created_by: "Emily Johnson",
        },
        {
          id: 4,
          project_name: "AI Chatbot Integration",
          status: "in_progress",
          created_date: "2024-01-21",
          due_date: "2024-04-20",
          created_by: "Michael Brown",
        },
        {
          id: 5,
          project_name: "Data Analytics Dashboard",
          status: "completed",
          created_date: "2024-01-26",
          due_date: "2024-04-25",
          created_by: "Sophia Lee",
        },
        {
          id: 6,
          project_name: "HR Management System",
          status: "pending",
          created_date: "2024-01-31",
          due_date: "2024-04-30",
          created_by: "Chris Martin",
        },
        {
          id: 7,
          project_name: "Marketing Automation",
          status: "in_progress",
          created_date: "2024-02-05",
          due_date: "2024-05-05",
          created_by: "Jessica Wilson",
        },
        {
          id: 8,
          project_name: "Inventory Management",
          status: "completed",
          created_date: "2024-02-10",
          due_date: "2024-05-10",
          created_by: "James Anderson",
        },
        {
          id: 9,
          project_name: "Cybersecurity Audit",
          status: "pending",
          created_date: "2024-02-15",
          due_date: "2024-05-15",
          created_by: "Olivia Taylor",
        },
        {
          id: 10,
          project_name: "Social Media Campaign",
          status: "in_progress",
          created_date: "2024-02-20",
          due_date: "2024-05-20",
          created_by: "Emma Harris",
        },
        {
          id: 11,
          project_name: "Customer Feedback Analysis",
          status: "completed",
          created_date: "2024-02-25",
          due_date: "2024-05-25",
          created_by: "Daniel Moore",
        },
        {
          id: 12,
          project_name: "DevOps Pipeline Setup",
          status: "pending",
          created_date: "2024-03-01",
          due_date: "2024-05-30",
          created_by: "Liam Garcia",
        },
        {
          id: 13,
          project_name: "Mobile Game Launch",
          status: "in_progress",
          created_date: "2024-03-06",
          due_date: "2024-06-04",
          created_by: "Charlotte Martinez",
        },
        {
          id: 14,
          project_name: "Learning Management System",
          status: "completed",
          created_date: "2024-03-11",
          due_date: "2024-06-09",
          created_by: "Ethan Robinson",
        },
        {
          id: 15,
          project_name: "Blockchain Wallet Development",
          status: "pending",
          created_date: "2024-03-16",
          due_date: "2024-06-14",
          created_by: "Isabella Clark",
        },
        {
          id: 16,
          project_name: "Video Editing Software",
          status: "in_progress",
          created_date: "2024-03-21",
          due_date: "2024-06-19",
          created_by: "Matthew Rodriguez",
        },
        {
          id: 17,
          project_name: "Supply Chain Optimization",
          status: "completed",
          created_date: "2024-03-26",
          due_date: "2024-06-24",
          created_by: "Ava Lewis",
        },
        {
          id: 18,
          project_name: "Website SEO Improvement",
          status: "pending",
          created_date: "2024-03-31",
          due_date: "2024-06-29",
          created_by: "Sophia Hall",
        },
        {
          id: 19,
          project_name: "AR Shopping App",
          status: "in_progress",
          created_date: "2024-04-05",
          due_date: "2024-07-04",
          created_by: "Noah Perez",
        },
        {
          id: 20,
          project_name: "Website Redesign",
          status: "completed",
          created_date: "2024-04-10",
          due_date: "2024-07-09",
          created_by: "Ilias Rais",
        },
        {
          id: 21,
          project_name: "Mobile App Development",
          status: "pending",
          created_date: "2024-04-15",
          due_date: "2024-07-14",
          created_by: "Sarah Smith",
        },
        {
          id: 22,
          project_name: "Cloud Migration",
          status: "in_progress",
          created_date: "2024-04-20",
          due_date: "2024-07-19",
          created_by: "John Doe",
        },
        {
          id: 23,
          project_name: "E-commerce Platform",
          status: "completed",
          created_date: "2024-04-25",
          due_date: "2024-07-24",
          created_by: "Emily Johnson",
        },
        {
          id: 24,
          project_name: "AI Chatbot Integration",
          status: "pending",
          created_date: "2024-04-30",
          due_date: "2024-07-29",
          created_by: "Michael Brown",
        },
        {
          id: 25,
          project_name: "Data Analytics Dashboard",
          status: "in_progress",
          created_date: "2024-05-05",
          due_date: "2024-08-03",
          created_by: "Sophia Lee",
        },
        {
          id: 26,
          project_name: "HR Management System",
          status: "completed",
          created_date: "2024-05-10",
          due_date: "2024-08-08",
          created_by: "Chris Martin",
        },
        {
          id: 27,
          project_name: "Marketing Automation",
          status: "pending",
          created_date: "2024-05-15",
          due_date: "2024-08-13",
          created_by: "Jessica Wilson",
        },
        {
          id: 28,
          project_name: "Inventory Management",
          status: "in_progress",
          created_date: "2024-05-20",
          due_date: "2024-08-18",
          created_by: "James Anderson",
        },
        {
          id: 29,
          project_name: "Cybersecurity Audit",
          status: "completed",
          created_date: "2024-05-25",
          due_date: "2024-08-23",
          created_by: "Olivia Taylor",
        },
        {
          id: 30,
          project_name: "Social Media Campaign",
          status: "pending",
          created_date: "2024-05-30",
          due_date: "2024-08-28",
          created_by: "Emma Harris",
        },
        {
          id: 31,
          project_name: "Customer Feedback Analysis",
          status: "in_progress",
          created_date: "2024-06-04",
          due_date: "2024-09-02",
          created_by: "Daniel Moore",
        },
        {
          id: 32,
          project_name: "DevOps Pipeline Setup",
          status: "completed",
          created_date: "2024-06-09",
          due_date: "2024-09-07",
          created_by: "Liam Garcia",
        },
        {
          id: 33,
          project_name: "Mobile Game Launch",
          status: "pending",
          created_date: "2024-06-14",
          due_date: "2024-09-12",
          created_by: "Charlotte Martinez",
        },
        {
          id: 34,
          project_name: "Learning Management System",
          status: "in_progress",
          created_date: "2024-06-19",
          due_date: "2024-09-17",
          created_by: "Ethan Robinson",
        },
        {
          id: 35,
          project_name: "Blockchain Wallet Development",
          status: "completed",
          created_date: "2024-06-24",
          due_date: "2024-09-22",
          created_by: "Isabella Clark",
        },
        {
          id: 36,
          project_name: "Video Editing Software",
          status: "pending",
          created_date: "2024-06-29",
          due_date: "2024-09-27",
          created_by: "Matthew Rodriguez",
        },
        {
          id: 37,
          project_name: "Supply Chain Optimization",
          status: "in_progress",
          created_date: "2024-07-04",
          due_date: "2024-10-02",
          created_by: "Ava Lewis",
        },
        {
          id: 38,
          project_name: "Website SEO Improvement",
          status: "completed",
          created_date: "2024-07-09",
          due_date: "2024-10-07",
          created_by: "Sophia Hall",
        },
        {
          id: 39,
          project_name: "AR Shopping App",
          status: "pending",
          created_date: "2024-07-14",
          due_date: "2024-10-12",
          created_by: "Noah Perez",
        },
        {
          id: 40,
          project_name: "Website Redesign",
          status: "in_progress",
          created_date: "2024-07-19",
          due_date: "2024-10-17",
          created_by: "Ilias Rais",
        },
        {
          id: 41,
          project_name: "Mobile App Development",
          status: "completed",
          created_date: "2024-07-24",
          due_date: "2024-10-22",
          created_by: "Sarah Smith",
        },
        {
          id: 42,
          project_name: "Cloud Migration",
          status: "pending",
          created_date: "2024-07-29",
          due_date: "2024-10-27",
          created_by: "John Doe",
        },
        {
          id: 43,
          project_name: "E-commerce Platform",
          status: "in_progress",
          created_date: "2024-08-03",
          due_date: "2024-11-01",
          created_by: "Emily Johnson",
        },
        {
          id: 44,
          project_name: "AI Chatbot Integration",
          status: "completed",
          created_date: "2024-08-08",
          due_date: "2024-11-06",
          created_by: "Michael Brown",
        },
        {
          id: 45,
          project_name: "Data Analytics Dashboard",
          status: "pending",
          created_date: "2024-08-13",
          due_date: "2024-11-11",
          created_by: "Sophia Lee",
        },
        {
          id: 46,
          project_name: "HR Management System",
          status: "in_progress",
          created_date: "2024-08-18",
          due_date: "2024-11-16",
          created_by: "Chris Martin",
        },
        {
          id: 47,
          project_name: "Marketing Automation",
          status: "completed",
          created_date: "2024-08-23",
          due_date: "2024-11-21",
          created_by: "Jessica Wilson",
        },
        {
          id: 48,
          project_name: "Inventory Management",
          status: "pending",
          created_date: "2024-08-28",
          due_date: "2024-11-26",
          created_by: "James Anderson",
        },
        {
          id: 49,
          project_name: "Cybersecurity Audit",
          status: "in_progress",
          created_date: "2024-09-02",
          due_date: "2024-12-01",
          created_by: "Olivia Taylor",
        },
        {
          id: 50,
          project_name: "Social Media Campaign",
          status: "completed",
          created_date: "2024-09-07",
          due_date: "2024-12-06",
          created_by: "Emma Harris",
        },
        {
          id: 51,
          project_name: "Customer Feedback Analysis",
          status: "pending",
          created_date: "2024-09-12",
          due_date: "2024-12-11",
          created_by: "Daniel Moore",
        },
        {
          id: 52,
          project_name: "DevOps Pipeline Setup",
          status: "in_progress",
          created_date: "2024-09-17",
          due_date: "2024-12-16",
          created_by: "Liam Garcia",
        },
        {
          id: 53,
          project_name: "Mobile Game Launch",
          status: "completed",
          created_date: "2024-09-22",
          due_date: "2024-12-21",
          created_by: "Charlotte Martinez",
        },
        {
          id: 54,
          project_name: "Learning Management System",
          status: "pending",
          created_date: "2024-09-27",
          due_date: "2024-12-26",
          created_by: "Ethan Robinson",
        },
        {
          id: 55,
          project_name: "Blockchain Wallet Development",
          status: "in_progress",
          created_date: "2024-10-02",
          due_date: "2024-12-31",
          created_by: "Isabella Clark",
        },
        {
          id: 56,
          project_name: "Video Editing Software",
          status: "completed",
          created_date: "2024-10-07",
          due_date: "2025-01-05",
          created_by: "Matthew Rodriguez",
        },
        {
          id: 57,
          project_name: "Supply Chain Optimization",
          status: "pending",
          created_date: "2024-10-12",
          due_date: "2025-01-10",
          created_by: "Ava Lewis",
        },
        {
          id: 58,
          project_name: "Website SEO Improvement",
          status: "in_progress",
          created_date: "2024-10-17",
          due_date: "2025-01-15",
          created_by: "Sophia Hall",
        },
        {
          id: 59,
          project_name: "AR Shopping App",
          status: "completed",
          created_date: "2024-10-22",
          due_date: "2025-01-20",
          created_by: "Noah Perez",
        },
        {
          id: 60,
          project_name: "Website Redesign",
          status: "pending",
          created_date: "2024-10-27",
          due_date: "2025-01-25",
          created_by: "Ilias Rais",
        },
        {
          id: 61,
          project_name: "Mobile App Development",
          status: "in_progress",
          created_date: "2024-11-01",
          due_date: "2025-01-30",
          created_by: "Sarah Smith",
        },
        {
          id: 62,
          project_name: "Cloud Migration",
          status: "completed",
          created_date: "2024-11-06",
          due_date: "2025-02-04",
          created_by: "John Doe",
        },
        {
          id: 63,
          project_name: "E-commerce Platform",
          status: "pending",
          created_date: "2024-11-11",
          due_date: "2025-02-09",
          created_by: "Emily Johnson",
        },
        {
          id: 64,
          project_name: "AI Chatbot Integration",
          status: "in_progress",
          created_date: "2024-11-16",
          due_date: "2025-02-14",
          created_by: "Michael Brown",
        },
        {
          id: 65,
          project_name: "Data Analytics Dashboard",
          status: "completed",
          created_date: "2024-11-21",
          due_date: "2025-02-19",
          created_by: "Sophia Lee",
        },
        {
          id: 66,
          project_name: "HR Management System",
          status: "pending",
          created_date: "2024-11-26",
          due_date: "2025-02-24",
          created_by: "Chris Martin",
        },
        {
          id: 67,
          project_name: "Marketing Automation",
          status: "in_progress",
          created_date: "2024-12-01",
          due_date: "2025-03-01",
          created_by: "Jessica Wilson",
        },
        {
          id: 68,
          project_name: "Inventory Management",
          status: "completed",
          created_date: "2024-12-06",
          due_date: "2025-03-06",
          created_by: "James Anderson",
        },
        {
          id: 69,
          project_name: "Cybersecurity Audit",
          status: "pending",
          created_date: "2024-12-11",
          due_date: "2025-03-11",
          created_by: "Olivia Taylor",
        },
        {
          id: 70,
          project_name: "Social Media Campaign",
          status: "in_progress",
          created_date: "2024-12-16",
          due_date: "2025-03-16",
          created_by: "Emma Harris",
        },
        {
          id: 71,
          project_name: "Customer Feedback Analysis",
          status: "completed",
          created_date: "2024-12-21",
          due_date: "2025-03-21",
          created_by: "Daniel Moore",
        },
        {
          id: 72,
          project_name: "DevOps Pipeline Setup",
          status: "pending",
          created_date: "2024-12-26",
          due_date: "2025-03-26",
          created_by: "Liam Garcia",
        },
        {
          id: 73,
          project_name: "Mobile Game Launch",
          status: "in_progress",
          created_date: "2024-12-31",
          due_date: "2025-03-31",
          created_by: "Charlotte Martinez",
        },
        {
          id: 74,
          project_name: "Learning Management System",
          status: "completed",
          created_date: "2025-01-05",
          due_date: "2025-04-05",
          created_by: "Ethan Robinson",
        },
        {
          id: 75,
          project_name: "Blockchain Wallet Development",
          status: "pending",
          created_date: "2025-01-10",
          due_date: "2025-04-10",
          created_by: "Isabella Clark",
        },
        {
          id: 76,
          project_name: "Video Editing Software",
          status: "in_progress",
          created_date: "2025-01-15",
          due_date: "2025-04-15",
          created_by: "Matthew Rodriguez",
        },
        {
          id: 77,
          project_name: "Supply Chain Optimization",
          status: "completed",
          created_date: "2025-01-20",
          due_date: "2025-04-20",
          created_by: "Ava Lewis",
        },
        {
          id: 78,
          project_name: "Website SEO Improvement",
          status: "pending",
          created_date: "2025-01-25",
          due_date: "2025-04-25",
          created_by: "Sophia Hall",
        },
        {
          id: 79,
          project_name: "AR Shopping App",
          status: "in_progress",
          created_date: "2025-01-30",
          due_date: "2025-04-30",
          created_by: "Noah Perez",
        },
        {
          id: 80,
          project_name: "Website Redesign",
          status: "completed",
          created_date: "2025-02-04",
          due_date: "2025-05-05",
          created_by: "Ilias Rais",
        },
        {
          id: 81,
          project_name: "Mobile App Development",
          status: "pending",
          created_date: "2025-02-09",
          due_date: "2025-05-10",
          created_by: "Sarah Smith",
        },
        {
          id: 82,
          project_name: "Cloud Migration",
          status: "in_progress",
          created_date: "2025-02-14",
          due_date: "2025-05-15",
          created_by: "John Doe",
        },
        {
          id: 83,
          project_name: "E-commerce Platform",
          status: "completed",
          created_date: "2025-02-19",
          due_date: "2025-05-20",
          created_by: "Emily Johnson",
        },
        {
          id: 84,
          project_name: "AI Chatbot Integration",
          status: "pending",
          created_date: "2025-02-24",
          due_date: "2025-05-25",
          created_by: "Michael Brown",
        },
        {
          id: 85,
          project_name: "Data Analytics Dashboard",
          status: "in_progress",
          created_date: "2025-03-01",
          due_date: "2025-05-30",
          created_by: "Sophia Lee",
        },
        {
          id: 86,
          project_name: "HR Management System",
          status: "completed",
          created_date: "2025-03-06",
          due_date: "2025-06-04",
          created_by: "Chris Martin",
        },
        {
          id: 87,
          project_name: "Marketing Automation",
          status: "pending",
          created_date: "2025-03-11",
          due_date: "2025-06-09",
          created_by: "Jessica Wilson",
        },
        {
          id: 88,
          project_name: "Inventory Management",
          status: "in_progress",
          created_date: "2025-03-16",
          due_date: "2025-06-14",
          created_by: "James Anderson",
        },
        {
          id: 89,
          project_name: "Cybersecurity Audit",
          status: "completed",
          created_date: "2025-03-21",
          due_date: "2025-06-19",
          created_by: "Olivia Taylor",
        },
        {
          id: 90,
          project_name: "Social Media Campaign",
          status: "pending",
          created_date: "2025-03-26",
          due_date: "2025-06-24",
          created_by: "Emma Harris",
        },
        {
          id: 91,
          project_name: "Customer Feedback Analysis",
          status: "in_progress",
          created_date: "2025-03-31",
          due_date: "2025-06-29",
          created_by: "Daniel Moore",
        },
        {
          id: 92,
          project_name: "DevOps Pipeline Setup",
          status: "completed",
          created_date: "2025-04-05",
          due_date: "2025-07-04",
          created_by: "Liam Garcia",
        },
        {
          id: 93,
          project_name: "Mobile Game Launch",
          status: "pending",
          created_date: "2025-04-10",
          due_date: "2025-07-09",
          created_by: "Charlotte Martinez",
        },
        {
          id: 94,
          project_name: "Learning Management System",
          status: "in_progress",
          created_date: "2025-04-15",
          due_date: "2025-07-14",
          created_by: "Ethan Robinson",
        },
        {
          id: 95,
          project_name: "Blockchain Wallet Development",
          status: "completed",
          created_date: "2025-04-20",
          due_date: "2025-07-19",
          created_by: "Isabella Clark",
        },
        {
          id: 96,
          project_name: "Video Editing Software",
          status: "pending",
          created_date: "2025-04-25",
          due_date: "2025-07-24",
          created_by: "Matthew Rodriguez",
        },
        {
          id: 97,
          project_name: "Supply Chain Optimization",
          status: "in_progress",
          created_date: "2025-04-30",
          due_date: "2025-07-29",
          created_by: "Ava Lewis",
        },
        {
          id: 98,
          project_name: "Website SEO Improvement",
          status: "completed",
          created_date: "2025-05-05",
          due_date: "2025-08-03",
          created_by: "Sophia Hall",
        },
        {
          id: 99,
          project_name: "AR Shopping App",
          status: "pending",
          created_date: "2025-05-10",
          due_date: "2025-08-08",
          created_by: "Noah Perez",
        },
        {
          id: 100,
          project_name: "Website Redesign",
          status: "in_progress",
          created_date: "2025-05-15",
          due_date: "2025-08-13",
          created_by: "Ilias Rais",
        },
      ]);
    }
  };

  useEffect(() => {
    fetchProjects();
  }, []);

  return (
    <div className="flex flex-col gap-9 mx-auto max-w-[1520px] px-4 sm:px-6 lg:px-8 py-[40px]">
      <div className="flex flex-col w-full gap-[12px]">
        <DataTable
          columns={columns}
          data={projects}
          onProjectUpdate={fetchProjects}
          onProjectDelete={fetchProjects}
        />
      </div>
    </div>
  );
}
